#!/usr/bin/env python3
"""
Fast & Memory-Optimized OCR Script for Raspberry Pi 4 (4GB RAM).
- Uses existing 'bays.json' generated by auto-detect script.
- Evaluates occupancy on 'testCurrent.jpg' vs 'testEmpty.jpg'.
- ONLY crops and runs EasyOCR on individual OCCUPIED bays.
- Enforces single-threaded PyTorch execution & manual garbage collection to prevent OOM/segmentation faults.
"""

import os

# --- CRITICAL: Set CPU threading limits BEFORE importing PyTorch/EasyOCR ---
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import gc
import json
import re
import time
import cv2
import easyocr
import numpy as np
import torch
from skimage.metrics import structural_similarity as ssim

# Force single-thread execution internally
torch.set_num_threads(1)
cv2.setNumThreads(1)

# -------- thresholds & settings --------
SSIM_MIN = 0.85
SAT_DELTA_MIN = 50.0
LUMA_DELTA_MIN = 50.0
CENTER_SIGMA_FRAC = 0.25
RESIZE_TO = (120, 120)
# ---------------------------------------

print("Initializing OCR Engine")
reader = easyocr.Reader(["en"], gpu=False)


# ==================== STEP 1: HELPER FUNCTIONS ==================== #
def load_bays(path):
    with open(path, "r") as f:
        return json.load(f)


def crop_polygon(img, points):
    """Crops the exact polygon region of a bay from the full image frame."""
    mask = np.zeros(img.shape[:2], dtype=np.uint8)
    pts = np.array(points, np.int32)
    cv2.fillPoly(mask, [pts], 255)
    x, y, w, h = cv2.boundingRect(pts)
    roi = cv2.bitwise_and(img, img, mask=mask)[y : y + h, x : x + w]
    return roi


def center_weight(h, w, sigma_frac=CENTER_SIGMA_FRAC):
    y, x = np.ogrid[:h, :w]
    cx, cy = (w - 1) / 2, (h - 1) / 2
    sigma = min(w, h) * sigma_frac
    wgt = np.exp(-((x - cx) ** 2 + (y - cy) ** 2) / (2 * sigma * sigma))
    return wgt / (wgt.mean() + 1e-9)


def patch_metrics(ref_patch, cur_patch):
    ref = cv2.resize(ref_patch, RESIZE_TO)
    cur = cv2.resize(cur_patch, RESIZE_TO)
    ref_hsv = cv2.cvtColor(ref, cv2.COLOR_BGR2HSV)
    cur_hsv = cv2.cvtColor(cur, cv2.COLOR_BGR2HSV)
    ref_v, ref_s = (
        ref_hsv[..., 2].astype(np.float32),
        ref_hsv[..., 1].astype(np.float32),
    )
    cur_v, cur_s = (
        cur_hsv[..., 2].astype(np.float32),
        cur_hsv[..., 1].astype(np.float32),
    )

    H, W = RESIZE_TO[1], RESIZE_TO[0]
    WGT = center_weight(H, W)

    ref_g = cv2.cvtColor(ref, cv2.COLOR_BGR2GRAY)
    cur_g = cv2.cvtColor(cur, cv2.COLOR_BGR2GRAY)
    s, diff = ssim(ref_g, cur_g, full=True)
    diff = 1.0 - diff
    s_weighted = 1.0 - float((diff * WGT).mean())

    sat_delta = float(((cur_s - ref_s) * WGT).mean())
    luma_delta = float(((cur_v - ref_v) * WGT).mean())

    return s_weighted, abs(sat_delta), luma_delta


def parse_id_from_name(name, fallback):
    m = re.search(r"(\d+)$", name)
    return int(m.group(1)) if m else fallback


# ==================== STEP 2: CROPPED BAY OCR (ROTATION-AWARE) ==================== #
def extract_plate_from_bay_crop(bay_crop):
    """
    Rotates the cropped patch in 90-degree increments (0°, 90°, 180°, 270°)
    and runs EasyOCR to detect vertically or upside-down oriented license plates.
    """
    if bay_crop is None or bay_crop.size == 0:
        return None

    gray = cv2.cvtColor(bay_crop, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape[:2]

    if h < 10 or w < 10:
        return None

    # Upscale crop slightly for clearer text recognition
    upscaled = cv2.resize(gray, (0, 0), fx=1.5, fy=1.5)

    # 4 rotation angles: Original, 90° Clockwise, 180°, 270° Clockwise (90° Counter-Clockwise)
    rotations = [
        upscaled,
        cv2.rotate(upscaled, cv2.ROTATE_90_CLOCKWISE),
        cv2.rotate(upscaled, cv2.ROTATE_180),
        cv2.rotate(upscaled, cv2.ROTATE_90_COUNTERCLOCKWISE),
    ]

    for rotated_img in rotations:
        ocr_results = reader.readtext(
            rotated_img,
            allowlist="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
            detail=0,
            canvas_size=600,
            workers=0,    # Preserves RAM stability
            batch_size=1, # Evaluates single patch
        )

        if not ocr_results:
            continue

        raw_text = "".join(ocr_results).upper().replace(" ", "")

        # 1. First priority: Exact 6-character alphanumeric match (e.g., REDBUL, 911GT3, SONY67)
        matches = re.findall(r"[A-Z0-9]{6}", raw_text)
        if matches:
            return matches[0]

        # 2. Fallback: If OCR catches at least 4 characters clearly
        if len(raw_text) >= 4:
            return raw_text[:6]

    return None

# ==================== STEP 3: OCCUPANCY & OCR ANALYSIS ==================== #
def analyze_and_prepare_payload(
    bays_path, ref_path, img_path, status_img_path="testBayStatusOCR.jpg"
):
    bays = load_bays(bays_path)
    ref = cv2.imread(ref_path)
    cur = cv2.imread(img_path)

    if ref is None or cur is None:
        raise SystemExit(
            f"Could not read reference image ({ref_path}) or current image ({img_path})"
        )

    payload = []
    fallback_id = 0
    annotated = cur.copy()

    for b in bays:
        pts = b["points"]
        ref_p = crop_polygon(ref, pts)
        cur_p = crop_polygon(cur, pts)

        if ref_p.size == 0 or cur_p.size == 0:
            continue

        # 1. Evaluate Bay Occupancy
        s_w, d_sat, d_luma = patch_metrics(ref_p, cur_p)
        adj_luma = abs(d_luma)
        taken = (
            (s_w < SSIM_MIN)
            or (d_sat > SAT_DELTA_MIN)
            or (adj_luma > LUMA_DELTA_MIN)
        )

        bay_id = parse_id_from_name(b["name"], fallback_id)
        fallback_id += 1

        plate = None

        # 2. Run OCR ONLY if spot is taken
        if taken:
            t0 = time.time()
            plate = extract_plate_from_bay_crop(cur_p)
            print(
                f"Bay #{bay_id} [TAKEN]: OCR finished in {time.time() - t0:.2f}s | Plate: {plate}"
            )

        bay_data = {
            "id": bay_id,
            "taken": bool(taken),
            "plate": plate,
        }
        payload.append(bay_data)

        # Draw visual annotations on preview output
        color = (0, 0, 255) if taken else (0, 255, 0)
        pts_arr = np.array(pts, np.int32)
        cv2.polylines(annotated, [pts_arr], True, color, 2)

        p = pts_arr[0]
        display_text = f"{bay_id}"
        if plate:
            display_text += f": {plate}"

        cv2.putText(
            annotated,
            display_text,
            (p[0] + 5, p[1] + 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            color,
            2,
        )

    cv2.imwrite(status_img_path, annotated)
    return payload


def format_json_multiline(data):
    lines = ["["]
    for i, item in enumerate(data):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  {json.dumps(item, separators=(", ", ": "))}{comma}')
    lines.append("]")
    return "\n".join(lines)


# ==================== MAIN EXECUTION ==================== #
def main():
    json_bays = "bays.json"
    empty_ref = "testEmpty.jpg"
    current_img = "testCurrent.jpg"
    status_img = "testBayStatusOCR.jpg"
    interval = 2

    print("Running testOCR.py (Pi 4 Stable Mode)...\n")

    if not os.path.exists(json_bays):
        print(f"Error: '{json_bays}' not found! Run auto-detect script first.")
        return

    print("Starting occupancy & OCR loop...")

    while True:
        try:
            if not os.path.exists(current_img) or not os.path.exists(empty_ref):
                print(f"Waiting for images to exist...")
                time.sleep(2)
                continue

            spots_data = analyze_and_prepare_payload(
                json_bays, empty_ref, current_img, status_img_path=status_img
            )

            print(format_json_multiline(spots_data))
            print(f"Saved preview to {status_img}\n")

            # Clean memory at the end of every loop iteration
            gc.collect()

            time.sleep(interval)

        except Exception as e:
            print("Loop Error:", e)
            time.sleep(2)


if __name__ == "__main__":
    main()